# version: "3.9"

services:
  api:
    build: ./services/api
    env_file: .env
    depends_on: [db, redis]
    ports: ["8000:8000"]
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
  worker:
    build: ./services/api
    env_file: .env
    depends_on: [db, redis]
    command: celery -A app.celery_app worker --loglevel=INFO
  

  scheduler:
    build: ./services/api
    env_file: .env
    depends_on: [db, redis]
    command: python -m app.scheduler 

  db:
    image: timescale/timescaledb:latest-pg16
    environment:
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pragyan
    ports: ["5433:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    ports: ["6379:6379"]

volumes:
  pgdata:

     