"""Added a separate table for trading universe

Revision ID: 287668a39ac8
Revises: 8d077d30a1d8
Create Date: 2025-09-22 22:53:49.682387

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '287668a39ac8'
down_revision: Union[str, Sequence[str], None] = '8d077d30a1d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('trading_universe',
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('asof_time', sa.String(length=8), nullable=False),
    sa.Column('symbol_id', sa.Integer(), nullable=False),
    sa.Column('instrument_token', sa.String(length=16), nullable=True),
    sa.Column('atr_pct', sa.Numeric(precision=6, scale=3), nullable=True),
    sa.Column('adv20', sa.Numeric(precision=18, scale=2), nullable=True),
    sa.Column('score', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['symbol_id'], ['symbols.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('date', 'asof_time', 'symbol_id', name='pk_trading_universe'),
    sa.UniqueConstraint('date', 'asof_time', 'symbol_id', name='uq_universe_snapshot_key')
    )
    op.create_index('ix_universe_date_asof_rank', 'trading_universe', ['date', 'asof_time', 'rank'], unique=False)
    op.create_index('ix_universe_date_asof_score', 'trading_universe', ['date', 'asof_time', 'score'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_universe_date_asof_score', table_name='trading_universe')
    op.drop_index('ix_universe_date_asof_rank', table_name='trading_universe')
    op.drop_table('trading_universe')
    # ### end Alembic commands ###
