"""Added adtv and atr_pct into features table

Revision ID: 63da77ab1c8c
Revises: 6fc0678590bf
Create Date: 2025-09-20 15:00:51.050687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63da77ab1c8c'
down_revision: Union[str, Sequence[str], None] = '6fc0678590bf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('features', sa.Column('atr_pct', sa.Numeric(precision=10, scale=4), nullable=True))
    op.add_column('features', sa.Column('adtv', sa.Numeric(precision=10, scale=4), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('features', 'adtv')
    op.drop_column('features', 'atr_pct')
    # ### end Alembic commands ###
