"""sync models with base schema

Revision ID: 6fc0678590bf
Revises: ad0a6ba91330
Create Date: 2025-09-05 16:49:00.519658

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6fc0678590bf'
down_revision: Union[str, Sequence[str], None] = 'ad0a6ba91330'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('candles_ts_idx'), table_name='candles')
    op.add_column('symbols', sa.Column('instrument_token', sa.String(length=16), nullable=False))
    op.add_column('symbols', sa.Column('last_price', sa.Numeric(precision=10, scale=4), nullable=False))
    op.drop_column('symbols', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('symbols', sa.Column('is_active', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=False))
    op.drop_column('symbols', 'last_price')
    op.drop_column('symbols', 'instrument_token')
    op.create_index(op.f('candles_ts_idx'), 'candles', [sa.literal_column('ts DESC')], unique=False)
    # ### end Alembic commands ###
