"""Minor Updates to data types

Revision ID: 8d077d30a1d8
Revises: 63da77ab1c8c
Create Date: 2025-09-20 15:23:03.925984

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d077d30a1d8'
down_revision: Union[str, Sequence[str], None] = '63da77ab1c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_candles_symbol_ts'), table_name='candles')
    op.create_index('ix_candles_symbol_tf_ts', 'candles', ['symbol_id', 'timeframe', 'ts'], unique=False)
    op.drop_index(op.f('idx_features_symbol_ts'), table_name='features')
    op.create_index('ix_features_symbol_ts', 'features', ['symbol_id', 'ts'], unique=False)
    op.add_column('symbols', sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False))
    op.alter_column('symbols', 'last_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=True)
    op.create_unique_constraint(None, 'symbols', ['instrument_token'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'symbols', type_='unique')
    op.alter_column('symbols', 'last_price',
               existing_type=sa.NUMERIC(precision=10, scale=4),
               nullable=False)
    op.drop_column('symbols', 'is_active')
    op.drop_index('ix_features_symbol_ts', table_name='features')
    op.create_index(op.f('idx_features_symbol_ts'), 'features', ['symbol_id', 'ts'], unique=False)
    op.drop_index('ix_candles_symbol_tf_ts', table_name='candles')
    op.create_index(op.f('ix_candles_symbol_ts'), 'candles', ['symbol_id', 'ts'], unique=False)
    # ### end Alembic commands ###
