"""create strategy signals table

Revision ID: ae1e840758d5
Revises: a1e6c7a4d328
Create Date: 2025-10-13 22:42:33.742240

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae1e840758d5'
down_revision: Union[str, Sequence[str], None] = 'a1e6c7a4d328'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    op.create_table(
        "strategy_signals",
        sa.Column("id", sa.Integer, primary_key=True),
        sa.Column("date", sa.Date, nullable=False),
        sa.Column("ts", sa.DateTime(timezone=True), nullable=False),
        sa.Column("symbol_id", sa.Integer, sa.ForeignKey("symbols.id"), nullable=False),
        sa.Column("instrument_token", sa.BigInteger, nullable=False),
        sa.Column("strategy_name", sa.String(length=50), nullable=False),
        sa.Column("side", sa.String(length=10), nullable=False),
        sa.Column("signal_strength", sa.Numeric(8, 4)),
        sa.Column("reason_codes", sa.ARRAY(sa.String())),
        sa.Column("entry_price", sa.Numeric(14, 4)),
        sa.Column("sl_price", sa.Numeric(14, 4)),
        sa.Column("tp_price", sa.Numeric(14, 4)),
        sa.Column("ttl_bars", sa.Integer, server_default="0"),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("NOW()")),
        sa.CheckConstraint("side IN ('long','short','flat')", name="ck_strategy_signals_side"),
    )
    op.create_index("ix_signals_symbol_ts", "strategy_signals", ["symbol_id", "ts"])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("DROP TABLE IF EXISTS strategy_signals")
    # ### end Alembic commands ###
